---
- name: Check if we already have a SSH key
  # http://docs.ansible.com/ansible/command_module.html
  command: ghe-config secrets.admin-ssh-pubkey
  register: repl_ssh_pre
  changed_when: false
  failed_when:
    # 0, no errors -> continue
    # 1, status warnings exist -> continue
    # 2, status errors exist -> fail
    - repl_ssh_pre.rc >= 2

- name: Save existing primary SSH key for later
  # http://docs.ansible.com/ansible/set_fact_module.html
  set_fact:
    replica_ssh_key: "{{ repl_ssh_pre.stdout }}"
  when: repl_ssh_pre.stdout

- name: Generate key the first time
  block:

  - name: Run ghe-repl-setup to generate keys
    # http://docs.ansible.com/ansible/command_module.html
    command: ghe-repl-setup -v "{{ github_host_ip }}"
    register: repl_setup_pre
    changed_when:
      # very first run
      - repl_setup_pre.rc == 255
    failed_when:
      # 0, no errors -> continue
      # 1, status warnings exist -> continue
      # 2, status errors exist -> fail
      - repl_setup_pre.rc >= 2

  - name: Get SSH key
    # http://docs.ansible.com/ansible/command_module.html
    command: ghe-config secrets.admin-ssh-pubkey
    register: repl_ssh
    changed_when: false

  - name: Save new primary SSH key for later
    # http://docs.ansible.com/ansible/set_fact_module.html
    set_fact:
      replica_ssh_key: "{{ repl_ssh.stdout }}"

  when: repl_ssh_pre.rc == 1

- name: Add SSH key to primary
  block:

  - name: Add SSH key to primary
    # http://docs.ansible.com/ansible/authorized_key_module.html
    authorized_key:
      user: admin
      key: "{{ replica_ssh_key }}"
      state: present

  - name: Run ghe-copy-authorized-keys on primary node
    # http://docs.ansible.com/ansible/command_module.html
    command: /usr/local/share/enterprise/ghe-copy-authorized-keys -r

  # We will need to look at this delegation,
  # as it makes the role inflexible
  delegate_to: primary

- name: Re-run ghe-repl-setup
  # http://docs.ansible.com/ansible/command_module.html
  command: ghe-repl-setup -v "{{ github_host_ip }}"
  changed_when: false
  register: repl_setup

- name: Start replication
  # http://docs.ansible.com/ansible/command_module.html
  command: ghe-repl-start -v
  # Dont wait for the command to finish
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html#concurrent-tasks-poll-0
  async: 1000
  poll: 0
  changed_when: false
  ignore_errors: true
  register: repl_start

- name: Verify replication
  block:

  - name: Verify replication startup
    # http://docs.ansible.com/ansible/async_status_module.html
    async_status:
      jid: "{{ repl_start.ansible_job_id }}"
    register: repl_start_result
    until: repl_start_result.finished
    retries: 100

  - name: Check replication status
    # http://docs.ansible.com/ansible/command_module.html
    command: ghe-repl-status
    register: repl_status
    # 0, no errors -> continue
    # 1, status warnings exist -> continue
    # 2, status errors exist -> fail
    failed_when: repl_status.rc >= 2
    changed_when: false

  when: verify_replication
